###
POST https://ideal-space-doodle-rqvpv97jjf5j5r-8000.app.github.dev/articles
content-type: application/json

{
    "title": "Health",
    "body": "Test"
}

###
GET https://ideal-space-doodle-rqvpv97jjf5j5r-8000.app.github.dev/articles

###
GET https://ideal-space-doodle-rqvpv97jjf5j5r-8000.app.github.dev/articles/1

###
PUT https://ideal-space-doodle-rqvpv97jjf5j5r-8000.app.github.dev/articles/1
content-type: application/json

{
    "title": "Healthy Lunch",
    "body": "Test"
}

###
DELETE https://ideal-space-doodle-rqvpv97jjf5j5r-8000.app.github.dev/articles/11
